### ISSUE TITLE
Is it possible to add some way to login using credentials to get cookie?

### ISSUE THREAD

**Issue by ChrisMGeo** [TIMMLOPK/genshin-kit.js#1]
The python library `genshin.py` has a method to login using the browser [here](https://thesadru.github.io/genshin.py/authentication/#example), (the docs forget to add `await`). Will it be possible to do the same with this library?

**Comment by TIMMLOPK** [comment]
Hi, genshin-kit.js can't do this now but it may be added in the next major release (v2), I would add it asap 😎

**Comment by TIMMLOPK** [comment]
Finished in v2,but it just support chrome now.

Example:
```js
    const manager = new ClientCookieManager();
    console.log(await manager .getBrowserCookie());
    const client = new Client({ cookieManager: manager });
```
